<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bittrade</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Contracts\Common\DomainCommon\Shared.Common.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\Spec\Exchanges\Bittrade\Normalized\Exchange.Bittrade.Normalized.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\**\*.cs" />
  </ItemGroup>

</Project>
