<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>exchangeapi</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Exchanges/Binance/Composition/ExchangeApi.Exchanges.Binance.Composition.csproj" />
    <ProjectReference Include="../../Exchanges/Bitflyer/Composition/ExchangeApi.Exchanges.Bitflyer.Composition.csproj" />
    <ProjectReference Include="../../Optional/Credentials/ExchangeApi.Optional.Credentials.csproj" />
  </ItemGroup>

</Project>
