<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>ExchangeApi.Factory</RootNamespace>
    <AssemblyName>ExchangeApi.Factory</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Common\\Common.csproj" />
    <ProjectReference Include="..\\Exchange.Bitflyer\\Exchange.Bitflyer.csproj" />
    <ProjectReference Include="..\\Exchange.Bittrade\\Exchange.Bittrade.csproj" />
  </ItemGroup>

</Project>
