<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <AssemblyName>ExchangeApi.Exchanges.Bittrade.Composition</AssemblyName>
    <RootNamespace>ExchangeApi.Exchanges.Bittrade.Composition</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adapter\ExchangeApi.Exchanges.Bittrade.Adapter.csproj" />
    <ProjectReference Include="..\..\..\Composition\ExchangeApi.Composition.csproj" />
  </ItemGroup>

</Project>
