<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bitflyer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Domain\Common\Common\Shared.Common.csproj" />
    <ProjectReference Include="..\..\..\Domain\Contracts\Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\Spec\Exchanges\Bitflyer\Raw\Exchange.Bitflyer.Raw.csproj" />
    <ProjectReference Include="..\..\..\Spec\Exchanges\Bitflyer\Normalized\Exchange.Bitflyer.Normalized.csproj" />
  </ItemGroup>

</Project>
