<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bitflyer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Contracts\Common\DomainCommon\Shared.Common.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\Spec\Exchanges\Bitflyer\Normalized\Exchange.Bitflyer.Normalized.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Common\ValueCommon\Spec.ValueCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Common\**\*.cs" />
  </ItemGroup>

</Project>
