<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>ExchangeApi.Utilities</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Common\ExchangeApi.Contracts.Common.csproj" />
    <ProjectReference Include="..\Primitives\ExchangeApi.Primitives.csproj" />
  </ItemGroup>

</Project>
