<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bittrade</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\..\Contracts\Common\DomainCommon\Shared.Common.csproj" />
    <ProjectReference Include="..\..\..\..\Contracts\Common\CallCommon\Spec.CallCommon.csproj" />
    <ProjectReference Include="..\..\..\..\Contracts\Common\JsonCommon\Spec.JsonCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Wire\**\*.cs" />
    <Compile Include="..\..\..\Wire\Common\WireResponse.cs" />
    <Compile Include="..\..\..\Wire\Common\WireCallSpec.cs" />
    <Compile Include="..\..\..\Wire\Common\IWireTransport.cs" />
    <Compile Include="..\..\..\Wire\Common\WireTransport.cs" />
  </ItemGroup>

</Project>
