<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bittrade</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\..\Domain\Common\Common\Shared.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Wire\**\*.cs" />
    <Compile Include="..\..\..\Wire\WireResponse.cs" />
    <Compile Include="..\..\..\Wire\WireRequest.cs" />
    <Compile Include="..\..\..\Wire\WireCall.cs" />
    <Compile Include="..\..\..\CallCommon\**\*.cs" />
  </ItemGroup>

</Project>
