<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Common.Core\\Common.Core.csproj" />
    <ProjectReference Include="..\\Exchange.Bitflyer\\ExchangeApi.Adapter.Bitflyer.csproj" />
    <ProjectReference Include="..\\Exchange.Bittrade\\ExchangeApi.Adapter.Bittrade.csproj" />
    <ProjectReference Include="..\\Exchange.Factory\\Exchange.Factory.csproj" />
  </ItemGroup>

</Project>
