<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <AssemblyName>ExchangeApi.Exchanges.Bitflyer.Adapter</AssemblyName>
    <RootNamespace>ExchangeApi.Exchanges.Bitflyer.Adapter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Normalized\ExchangeApi.Exchanges.Bitflyer.Normalized.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Facade\ExchangeApi.Contracts.Facade.csproj" />
    <ProjectReference Include="..\..\..\Primitives\ExchangeApi.Primitives.csproj" />
    <ProjectReference Include="..\..\..\Utilities\ExchangeApi.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Common\Application\Adapter\**\*.cs" Link="Common/Adapter/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
