<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>ExchangeApi.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Common/Common/Shared.Common.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**/bin/**/*.cs" />
    <Compile Remove="**/obj/**/*.cs" />
  </ItemGroup>

</Project>
