<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Exchanges\Bitflyer\Raw\Exchange.Bitflyer.Raw.csproj" />
    <ProjectReference Include="..\..\Exchanges\Bitflyer\Adapter\Exchange.Bitflyer.Adapter.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bitflyer</RootNamespace>
  </PropertyGroup>

</Project>
