<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\..\Common\Common.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\..\Core\Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Exchange.Bitflyer</RootNamespace>
  </PropertyGroup>

</Project>
