global using ExchangeApi.Transport.Wire;
global using ExchangeApi.Primitives.CallCommon;
global using ExchangeApi.Exchanges.Bittrade.Raw.Public.Api;
global using ExchangeApi.Exchanges.Bittrade.Raw.Public.Dtos;
global using ExchangeApi.Exchanges.Bittrade.Raw.Public.Requests;
global using ExchangeApi.Exchanges.Bittrade.Raw.Private.Api;
global using ExchangeApi.Exchanges.Bittrade.Raw.Private.Dtos;
global using ExchangeApi.Exchanges.Bittrade.Raw.Private.Requests;
global using ExchangeApi.Exchanges.Bittrade.Raw.Internal;
namespace ExchangeApi.Exchanges.Bittrade.Raw;
