<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <RootNamespace>Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Composition/Factory/MultiExchangeClient.cs" />
    <Compile Remove="Composition/Factory/MultiExchangeClientFactory.cs" />
    <Compile Remove="Composition/Factory/MultiExchangePublicClient.cs" />
    <Compile Remove="Composition/Factory/Unified/**/*.cs" />
    <Compile Remove="**/bin/**/*.cs" />
    <Compile Remove="**/obj/**/*.cs" />
  </ItemGroup>

</Project>
