<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <AssemblyName>ExchangeApi.Stage10.Bitflyer.Native</AssemblyName>
    <RootNamespace>ExchangeApi.Stage10.Bitflyer.Native</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Protocol/ExchangeApi.Stage10.Bitflyer.Protocol.csproj" />
    <ProjectReference Include="../../../src/Primitives/ExchangeApi.Primitives.csproj" />
  </ItemGroup>
</Project>
