<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <AssemblyName>ExchangeApi.Exchanges.Bitflyer.Api.Adapter</AssemblyName>
    <RootNamespace>ExchangeApi.Exchanges.Bitflyer.Api.Adapter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Normalized\ExchangeApi.Exchanges.Bitflyer.Normalized.csproj" />
    <ProjectReference Include="..\..\..\..\Contracts\Facade\ExchangeApi.Contracts.Facade.csproj" />
    <ProjectReference Include="..\..\..\..\Primitives\ExchangeApi.Primitives.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\ExchangeInfo\Adapter\**\*.cs" Link="ExchangeInfo/Adapter/%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\..\Common\ExchangeInfo\Adapter\**\*.cs" Link="Common/ExchangeInfo/Adapter/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
